AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack Template

Parameters:
   VpcIdOfSecurityGroup: 
    Type: AWS::EC2::VPC::Id

Resources: 
  mySecurityGroup: 
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: my ssh and http sg
        SecurityGroupIngress: 
         - IpProtocol: tcp
           FromPort: '22'
           ToPort: '22'
           CidrIp: 0.0.0.0/0
         - IpProtocol: tcp
           FromPort: '80'
           ToPort: '80'
           CidrIp: 0.0.0.0/0
        VpcId: !Ref VpcIdOfSecurityGroup

Outputs: 
   SecurityGroupId: 
     Description: SG id
     Value: !Ref mySecurityGroup
